[build]
  command = "cd server && npm install && cd .."
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[functions]
  directory = "server"
