[build]
  command = "cd server && npm install && cd .."
  publish = "."  # Publikuj główny folder

[[redirects]]
  from = "/images/*"
  to = "/public/images/:splat"
  status = 200

[functions]
  directory = "server"
